name: Daily AI News Update

on:
  schedule:
    # Runs every day at 8:00 AM UTC (adjust timezone as needed)
    - cron: '0 8 * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  update-ai-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run AI News Update
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
      run: python src/main.py
      
    - name: Commit and push if content changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if ! git diff --cached --quiet; then
          git commit -m "📰 Daily AI news update - $(date +'%Y-%m-%d')"
          git push
        else
          echo "No changes to commit"
        fi